/** Türkçe misafir ülke adı -> world-atlas topojson'daki `properties.name` (İngilizce) eşlemesi. */
export const COUNTRY_NAME_EN: Record<string, string> = {
  "Türkiye": "Turkey",
  "Almanya": "Germany",
  "Rusya": "Russia",
  "Birleşik Krallık": "United Kingdom",
  "Hollanda": "Netherlands",
  "Fransa": "France",
  "Ukrayna": "Ukraine",
  "İran": "Iran",
  "Bulgaristan": "Bulgaria",
  "Gürcistan": "Georgia",
  "Amerika Birleşik Devletleri": "United States of America",
  "İtalya": "Italy",
  "İspanya": "Spain",
  "Suudi Arabistan": "Saudi Arabia",
  "Birleşik Arap Emirlikleri": "United Arab Emirates",
  "Polonya": "Poland",
  "Yunanistan": "Greece",
  "Azerbaycan": "Azerbaijan",
  "Irak": "Iraq",
  "Kuveyt": "Kuwait",
  "Katar": "Qatar",
  "Belçika": "Belgium",
  "İsveç": "Sweden",
  "Avusturya": "Austria",
  "İsviçre": "Switzerland",
  "Romanya": "Romania",
  "Çek Cumhuriyeti": "Czechia",
  "Norveç": "Norway",
  "Danimarka": "Denmark",
  "Macaristan": "Hungary",
  "Portekiz": "Portugal",
  "Ürdün": "Jordan",
  "Lübnan": "Lebanon",
  "İsrail": "Israel",
  "Kıbrıs": "Cyprus",
  "Çin": "China",
  "Japonya": "Japan",
  "Güney Kore": "South Korea",
  "Hindistan": "India",
  "Kanada": "Canada",
  "Avustralya": "Australia",
  "Brezilya": "Brazil",
  "Meksika": "Mexico",
  "Fas": "Morocco",
  "Mısır": "Egypt",
  "Cezayir": "Algeria",
  "Tunus": "Tunisia",
  "Endonezya": "Indonesia",
  "Malezya": "Malaysia",
  "Tayland": "Thailand",
  "Arjantin": "Argentina",
  "Güney Afrika": "South Africa",
  "Kazakistan": "Kazakhstan",
  "Ermenistan": "Armenia",
  "Sırbistan": "Serbia",
  "Hırvatistan": "Croatia",
  "Finlandiya": "Finland",
  "İrlanda": "Ireland",
  "Vietnam": "Vietnam",
  "Filipinler": "Philippines",
  "Şili": "Chile",
  "Kolombiya": "Colombia",
  "Nijerya": "Nigeria",
  "Kenya": "Kenya",
  "Özbekistan": "Uzbekistan",
  "Slovenya": "Slovenia",
  "Slovakya": "Slovakia",
  "Yeni Zelanda": "New Zealand",
  "Pakistan": "Pakistan",
  "Umman": "Oman",
  "Kuzey Makedonya": "Macedonia",
  "Arnavutluk": "Albania",
  "Moldova": "Moldova",
  "Belarus": "Belarus",
  "Litvanya": "Lithuania",
  "Letonya": "Latvia",
  "Estonya": "Estonia",
  "Bangladeş": "Bangladesh",
};

export const COUNTRY_PHONE_CODES: Record<string, string> = {
  "Türkiye": "+90", "Almanya": "+49", "Rusya": "+7", "Birleşik Krallık": "+44",
  "Hollanda": "+31", "Fransa": "+33", "Ukrayna": "+380", "İran": "+98",
  "Bulgaristan": "+359", "Gürcistan": "+995", "Amerika Birleşik Devletleri": "+1",
  "İtalya": "+39", "İspanya": "+34", "Suudi Arabistan": "+966",
  "Birleşik Arap Emirlikleri": "+971", "Polonya": "+48", "Yunanistan": "+30",
  "Azerbaycan": "+994", "Irak": "+964", "Kuveyt": "+965", "Katar": "+974",
  "Belçika": "+32", "İsveç": "+46", "Avusturya": "+43", "İsviçre": "+41",
  "Romanya": "+40", "Çek Cumhuriyeti": "+420", "Norveç": "+47",
  "Danimarka": "+45", "Macaristan": "+36", "Portekiz": "+351",
  "Ürdün": "+962", "Lübnan": "+961", "İsrail": "+972", "Kıbrıs": "+357",
  "Çin": "+86", "Japonya": "+81", "Güney Kore": "+82", "Hindistan": "+91",
  "Kanada": "+1", "Avustralya": "+61", "Brezilya": "+55", "Meksika": "+52",
  "Fas": "+212", "Mısır": "+20", "Cezayir": "+213", "Tunus": "+216",
  "Endonezya": "+62", "Malezya": "+60", "Tayland": "+66", "Arjantin": "+54",
  "Güney Afrika": "+27", "Kazakistan": "+7", "Ermenistan": "+374",
  "Sırbistan": "+381", "Hırvatistan": "+385", "Finlandiya": "+358",
  "İrlanda": "+353", "Vietnam": "+84", "Filipinler": "+63", "Şili": "+56",
  "Kolombiya": "+57", "Nijerya": "+234", "Kenya": "+254", "Özbekistan": "+998",
  "Slovenya": "+386", "Slovakya": "+421", "Yeni Zelanda": "+64",
  "Pakistan": "+92", "Umman": "+968", "Kuzey Makedonya": "+389",
  "Arnavutluk": "+355", "Moldova": "+373", "Belarus": "+375",
  "Litvanya": "+370", "Letonya": "+371", "Estonya": "+372", "Bangladeş": "+880",
};
